object FormAllInOne: TFormAllInOne
  Left = 0
  Top = 0
  Caption = 'SkiaVclControlsFree - All-in-One Demo'
  ClientHeight = 1131
  ClientWidth = 1341
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Microsoft YaHei'
  Font.Style = []
  Position = poScreenCenter
  OnCreate = FormCreate
  TextHeight = 17
  object pnlMain: TDSkPanel
    Left = 0
    Top = 0
    Width = 1341
    Height = 1131
    Align = alClient
    Caption = ''
    CaptionPosition = cpTopLeft
    CaptionFont.Charset = DEFAULT_CHARSET
    CaptionFont.Color = clWindowText
    CaptionFont.Height = -12
    CaptionFont.Name = 'Microsoft YaHei'
    CaptionFont.Style = []
    CaptionMargin = 8.000000000000000000
    ChildPadding = 12.000000000000000000
    BackgroundHover = claWhitesmoke
    PanelStyle = psElevated
    CornerRadius = 12.000000000000000000
    BackgroundColor = claWhite
    BorderColor = xFFE0E0E0
    BorderWidth = 0.500000000000000000
    object pnlHeader: TDSkPanel
      Left = 12
      Top = 12
      Width = 1076
      Height = 50
      Caption = 'SkiaVclControlsFree - All-in-One Demo'
      CaptionPosition = cpLeftCenter
      CaptionFont.Charset = DEFAULT_CHARSET
      CaptionFont.Color = clWindowText
      CaptionFont.Height = -18
      CaptionFont.Name = 'Microsoft YaHei'
      CaptionFont.Style = []
      CaptionMargin = 8.000000000000000000
      ChildPadding = 8.000000000000000000
      BackgroundHover = claWhitesmoke
      PanelStyle = psElevated
      CornerRadius = 12.000000000000000000
      BackgroundColor = claWhite
      BorderColor = xFFE0E0E0
      BorderWidth = 0.500000000000000000
      object btnAbout: TDSkButton
        Left = 924
        Top = 3
        Width = 120
        Height = 34
        OnClick = btnAboutClick
        ButtonText = 'About'
        ButtonColor = xFF0288D1
        ButtonHover = xFF03A9F4
        ButtonPressed = xFF01579B
        ButtonDisabled = xFFBDBDBD
        ButtonChecked = xFF1565C0
        FontColor = claWhite
        FontHover = claWhite
        FontDisabled = xFF757575
        FontChecked = claWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Microsoft YaHei UI'
        Font.Style = []
        ButtonStyle = bsRoundRect
        ButtonType = btNormal
        ButtonRound = 10.000000000000000000
        Checked = False
        ImageIndex = -1
        ImageAlign = iaLeft
        ImageMargin = 8
        HoverEffect = heRipple
        MUIColorScheme = muiInfo
        MUIStyle = muiContained
        BackgroundColor = claWhite
        BorderColor = xFF0288D1
        BorderWidth = 0.000000000000000000
      end
    end
    object pnlContent: TDSkPanel
      Left = 12
      Top = 70
      Width = 1076
      Height = 618
      Caption = ''
      CaptionPosition = cpTopLeft
      CaptionFont.Charset = DEFAULT_CHARSET
      CaptionFont.Color = clWindowText
      CaptionFont.Height = -12
      CaptionFont.Name = 'Microsoft YaHei'
      CaptionFont.Style = []
      CaptionMargin = 8.000000000000000000
      ChildPadding = 12.000000000000000000
      BackgroundHover = claWhitesmoke
      PanelStyle = psOutlined
      CornerRadius = 12.000000000000000000
      BackgroundColor = claWhite
      BorderColor = xFFE0E0E0
      BorderWidth = 1.000000000000000000
      object pnlLeft: TDSkPanel
        Left = 12
        Top = 12
        Width = 620
        Height = 594
        Caption = ''
        CaptionPosition = cpTopLeft
        CaptionFont.Charset = DEFAULT_CHARSET
        CaptionFont.Color = clWindowText
        CaptionFont.Height = -12
        CaptionFont.Name = 'Microsoft YaHei'
        CaptionFont.Style = []
        CaptionMargin = 8.000000000000000000
        ChildPadding = 8.000000000000000000
        BackgroundHover = claWhitesmoke
        PanelStyle = psOutlined
        CornerRadius = 8.000000000000000000
        BackgroundColor = claWhite
        BorderColor = xFFE0E0E0
        BorderWidth = 1.000000000000000000
        object lblResult: TLabel
          Left = 0
          Top = 574
          Width = 620
          Height = 20
          Align = alBottom
          Alignment = taCenter
          AutoSize = False
          Caption = 'Result will appear here'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -12
          Font.Name = 'Microsoft YaHei'
          Font.Style = []
          ParentFont = False
          ExplicitLeft = 8
          ExplicitTop = 570
          ExplicitWidth = 604
        end
        object pnlButtons: TDSkPanel
          Left = 12
          Top = 7
          Width = 604
          Height = 55
          Caption = ''
          CaptionPosition = cpTopLeft
          CaptionFont.Charset = DEFAULT_CHARSET
          CaptionFont.Color = clWindowText
          CaptionFont.Height = -12
          CaptionFont.Name = 'Microsoft YaHei'
          CaptionFont.Style = []
          CaptionMargin = 4.000000000000000000
          ChildPadding = 4.000000000000000000
          BackgroundHover = claWhitesmoke
          PanelStyle = psOutlined
          CornerRadius = 6.000000000000000000
          BackgroundColor = claWhite
          BorderColor = xFFE0E0E0
          BorderWidth = 1.000000000000000000
          object btnPrimary: TDSkButton
            Left = 345
            Top = 11
            Width = 80
            Height = 32
            OnClick = btnPrimaryClick
            ButtonText = 'Primary'
            ButtonColor = xFF1976D2
            ButtonHover = xFF42A5F5
            ButtonPressed = xFF1565C0
            ButtonDisabled = xFFBDBDBD
            ButtonChecked = xFF1565C0
            FontColor = claWhite
            FontHover = claWhite
            FontDisabled = xFF757575
            FontChecked = claWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Microsoft YaHei UI'
            Font.Style = []
            ButtonStyle = bsRoundRect
            ButtonType = btNormal
            ButtonRound = 10.000000000000000000
            Checked = False
            ImageIndex = -1
            ImageAlign = iaLeft
            ImageMargin = 8
            HoverEffect = heRipple
            MUIColorScheme = muiPrimary
            MUIStyle = muiContained
            BackgroundColor = claWhite
            BorderColor = xFF1976D2
            BorderWidth = 0.000000000000000000
          end
          object btnSecondary: TDSkButton
            Left = 261
            Top = 11
            Width = 80
            Height = 32
            OnClick = btnSecondaryClick
            ButtonText = 'Secondary'
            ButtonColor = xFF9C27B0
            ButtonHover = xFFBA68C8
            ButtonPressed = xFF7B1FA2
            ButtonDisabled = xFFBDBDBD
            ButtonChecked = xFF1565C0
            FontColor = claWhite
            FontHover = claWhite
            FontDisabled = xFF757575
            FontChecked = claWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Microsoft YaHei UI'
            Font.Style = []
            ButtonStyle = bsRoundRect
            ButtonType = btNormal
            ButtonRound = 10.000000000000000000
            Checked = False
            ImageIndex = -1
            ImageAlign = iaLeft
            ImageMargin = 8
            HoverEffect = heRipple
            MUIColorScheme = muiSecondary
            MUIStyle = muiContained
            BackgroundColor = claWhite
            BorderColor = xFF9C27B0
            BorderWidth = 0.000000000000000000
          end
          object btnSuccess: TDSkButton
            Left = 177
            Top = 11
            Width = 80
            Height = 32
            OnClick = btnSuccessClick
            ButtonText = 'Success'
            ButtonColor = xFF2E7D32
            ButtonHover = xFF4CAF50
            ButtonPressed = xFF1B5E20
            ButtonDisabled = xFFBDBDBD
            ButtonChecked = xFF1565C0
            FontColor = claWhite
            FontHover = claWhite
            FontDisabled = xFF757575
            FontChecked = claWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Microsoft YaHei UI'
            Font.Style = []
            ButtonStyle = bsRoundRect
            ButtonType = btNormal
            ButtonRound = 10.000000000000000000
            Checked = False
            ImageIndex = -1
            ImageAlign = iaLeft
            ImageMargin = 8
            HoverEffect = heRipple
            MUIColorScheme = muiSuccess
            MUIStyle = muiContained
            BackgroundColor = claWhite
            BorderColor = xFF2E7D32
            BorderWidth = 0.000000000000000000
          end
          object btnWarning: TDSkButton
            Left = 93
            Top = 11
            Width = 80
            Height = 32
            OnClick = btnWarningClick
            ButtonText = 'Warning'
            ButtonColor = xFFED6C02
            ButtonHover = xFFFF9800
            ButtonPressed = xFFE65100
            ButtonDisabled = xFFBDBDBD
            ButtonChecked = xFF1565C0
            FontColor = claWhite
            FontHover = claWhite
            FontDisabled = xFF757575
            FontChecked = claWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Microsoft YaHei UI'
            Font.Style = []
            ButtonStyle = bsRoundRect
            ButtonType = btNormal
            ButtonRound = 10.000000000000000000
            Checked = False
            ImageIndex = -1
            ImageAlign = iaLeft
            ImageMargin = 8
            HoverEffect = heRipple
            MUIColorScheme = muiWarning
            MUIStyle = muiContained
            BackgroundColor = claWhite
            BorderColor = xFFED6C02
            BorderWidth = 0.000000000000000000
          end
          object btnDanger: TDSkButton
            Left = 429
            Top = 11
            Width = 80
            Height = 32
            OnClick = btnDangerClick
            ButtonText = 'Danger'
            ButtonColor = xFFD32F2F
            ButtonHover = xFFEF5350
            ButtonPressed = xFFC62828
            ButtonDisabled = xFFBDBDBD
            ButtonChecked = xFF1565C0
            FontColor = claWhite
            FontHover = claWhite
            FontDisabled = xFF757575
            FontChecked = claWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Microsoft YaHei UI'
            Font.Style = []
            ButtonStyle = bsRoundRect
            ButtonType = btNormal
            ButtonRound = 10.000000000000000000
            Checked = False
            ImageIndex = -1
            ImageAlign = iaLeft
            ImageMargin = 8
            HoverEffect = heRipple
            MUIColorScheme = muiError
            MUIStyle = muiContained
            BackgroundColor = claWhite
            BorderColor = xFFD32F2F
            BorderWidth = 0.000000000000000000
          end
          object btnInfo: TDSkButton
            Left = 513
            Top = 11
            Width = 80
            Height = 32
            OnClick = btnInfoClick
            ButtonText = 'Info'
            ButtonColor = xFF0288D1
            ButtonHover = xFF03A9F4
            ButtonPressed = xFF01579B
            ButtonDisabled = xFFBDBDBD
            ButtonChecked = xFF1565C0
            FontColor = claWhite
            FontHover = claWhite
            FontDisabled = xFF757575
            FontChecked = claWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Microsoft YaHei UI'
            Font.Style = []
            ButtonStyle = bsRoundRect
            ButtonType = btNormal
            ButtonRound = 10.000000000000000000
            Checked = False
            ImageIndex = -1
            ImageAlign = iaLeft
            ImageMargin = 8
            HoverEffect = heRipple
            MUIColorScheme = muiInfo
            MUIStyle = muiContained
            BackgroundColor = claWhite
            BorderColor = xFF0288D1
            BorderWidth = 0.000000000000000000
          end
          object btnToggle: TDSkButton
            Left = 9
            Top = 11
            Width = 80
            Height = 32
            OnClick = btnToggleClick
            ButtonText = 'Toggle'
            ButtonColor = xFF1976D2
            ButtonHover = xFF42A5F5
            ButtonPressed = xFF1565C0
            ButtonDisabled = xFFBDBDBD
            ButtonChecked = xFF1565C0
            FontColor = claWhite
            FontHover = claWhite
            FontDisabled = xFF757575
            FontChecked = claWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Microsoft YaHei UI'
            Font.Style = []
            ButtonStyle = bsRoundRect
            ButtonType = btToggle
            ButtonRound = 10.000000000000000000
            Checked = False
            ImageIndex = -1
            ImageAlign = iaLeft
            ImageMargin = 8
            HoverEffect = heRipple
            MUIColorScheme = muiPrimary
            MUIStyle = muiContained
            BackgroundColor = claWhite
            BorderColor = xFF1976D2
            BorderWidth = 0.000000000000000000
          end
        end
        object pnlRadios: TDSkPanel
          Left = 8
          Top = 68
          Width = 300
          Height = 364
          Caption = ''
          CaptionPosition = cpTopLeft
          CaptionFont.Charset = DEFAULT_CHARSET
          CaptionFont.Color = clWindowText
          CaptionFont.Height = -12
          CaptionFont.Name = 'Microsoft YaHei'
          CaptionFont.Style = []
          CaptionMargin = 4.000000000000000000
          ChildPadding = 4.000000000000000000
          BackgroundHover = claWhitesmoke
          PanelStyle = psOutlined
          CornerRadius = 6.000000000000000000
          BackgroundColor = claWhite
          BorderColor = xFFE0E0E0
          BorderWidth = 1.000000000000000000
          object rgColorScheme: TDSkRadioGroup
            AlignWithMargins = True
            Left = 3
            Top = 3
            Width = 294
            Height = 358
            Align = alClient
            Items.Strings = (
              'Primary'
              'Secondary'
              'Error'
              'Warning'
              'Info'
              'Success')
            Caption = 'Color Scheme'
            CaptionFont.Charset = DEFAULT_CHARSET
            CaptionFont.Color = clWindowText
            CaptionFont.Height = -12
            CaptionFont.Name = 'Microsoft YaHei'
            CaptionFont.Style = []
            CaptionMargin = 4.000000000000000000
            RadioSize = 16.000000000000000000
            ItemFont.Charset = DEFAULT_CHARSET
            ItemFont.Color = clWindowText
            ItemFont.Height = -12
            ItemFont.Name = 'Microsoft YaHei'
            ItemFont.Style = []
            OnItemClick = rgColorSchemeItemClick
            BackgroundColor = claNull
            BorderColor = claGray
            BorderWidth = 0.000000000000000000
          end
        end
        object pnlCheckboxes: TDSkPanel
          Left = 312
          Top = 68
          Width = 300
          Height = 364
          Caption = ''
          CaptionPosition = cpTopLeft
          CaptionFont.Charset = DEFAULT_CHARSET
          CaptionFont.Color = clWindowText
          CaptionFont.Height = -12
          CaptionFont.Name = 'Microsoft YaHei'
          CaptionFont.Style = []
          CaptionMargin = 4.000000000000000000
          ChildPadding = 4.000000000000000000
          BackgroundHover = claWhitesmoke
          PanelStyle = psOutlined
          CornerRadius = 6.000000000000000000
          BackgroundColor = claWhite
          BorderColor = xFFE0E0E0
          BorderWidth = 1.000000000000000000
          object cgFeatures: TDSkCheckboxGroup
            AlignWithMargins = True
            Left = 3
            Top = 3
            Width = 294
            Height = 358
            Align = alClient
            Items.Strings = (
              'Feature A - Basic'
              'Feature B - Advanced'
              'Feature C - Premium'
              'Feature D - Enterprise')
            Caption = 'Features'
            CaptionFont.Charset = DEFAULT_CHARSET
            CaptionFont.Color = clWindowText
            CaptionFont.Height = -12
            CaptionFont.Name = 'Microsoft YaHei'
            CaptionFont.Style = []
            CaptionMargin = 4.000000000000000000
            CheckboxSize = 16.000000000000000000
            ItemFont.Charset = DEFAULT_CHARSET
            ItemFont.Color = clWindowText
            ItemFont.Height = -12
            ItemFont.Name = 'Microsoft YaHei'
            ItemFont.Style = []
            OnItemClick = cgFeaturesItemClick
            BackgroundColor = claNull
            BorderColor = claGray
            BorderWidth = 0.000000000000000000
          end
        end
        object pnlSwitches: TDSkPanel
          Left = 0
          Top = 437
          Width = 620
          Height = 51
          Align = alBottom
          Caption = 'Switches'
          CaptionPosition = cpTopLeft
          CaptionFont.Charset = DEFAULT_CHARSET
          CaptionFont.Color = clWindowText
          CaptionFont.Height = -12
          CaptionFont.Name = 'Microsoft YaHei'
          CaptionFont.Style = []
          CaptionMargin = 4.000000000000000000
          ChildPadding = 4.000000000000000000
          BackgroundHover = claWhitesmoke
          PanelStyle = psOutlined
          CornerRadius = 6.000000000000000000
          BackgroundColor = claWhite
          BorderColor = xFFE0E0E0
          BorderWidth = 1.000000000000000000
          object swDarkMode: TDSkSwitch
            Left = 12
            Top = 20
            Width = 140
            Height = 24
            Caption = 'Dark Mode'
            Size = sssSmall
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Microsoft YaHei UI'
            Font.Style = []
            OnCheckChanged = swDarkModeSwitch
          end
          object swNotifications: TDSkSwitch
            Left = 170
            Top = 20
            Width = 150
            Height = 24
            Checked = True
            Caption = 'Notifications'
            Size = sssSmall
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Microsoft YaHei UI'
            Font.Style = []
            OnCheckChanged = swNotificationsSwitch
          end
          object swAutoSave: TDSkSwitch
            Left = 340
            Top = 20
            Width = 120
            Height = 24
            Checked = True
            Caption = 'Auto-Save'
            Size = sssSmall
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Microsoft YaHei UI'
            Font.Style = []
            OnCheckChanged = swAutoSaveSwitch
          end
        end
        object pnlButtonGroup: TDSkPanel
          AlignWithMargins = True
          Left = 3
          Top = 491
          Width = 614
          Height = 80
          Align = alBottom
          Caption = 'Button Group'
          CaptionPosition = cpTopLeft
          CaptionFont.Charset = DEFAULT_CHARSET
          CaptionFont.Color = clWindowText
          CaptionFont.Height = -12
          CaptionFont.Name = 'Microsoft YaHei'
          CaptionFont.Style = []
          CaptionMargin = 4.000000000000000000
          ChildPadding = 4.000000000000000000
          BackgroundHover = claWhitesmoke
          PanelStyle = psOutlined
          CornerRadius = 6.000000000000000000
          BackgroundColor = claWhite
          BorderColor = xFFE0E0E0
          BorderWidth = 1.000000000000000000
          object bgActions: TDSkButtonGroup
            Left = 8
            Top = 22
            Width = 588
            Height = 50
            Variant = bgvContained
            OnItemClick = bgActionsItemClick
            CornerRadius = 4.000000000000000000
            BackgroundColor = xFF1976D2
            BorderColor = x33000000
            BorderWidth = 0.000000000000000000
            object bgHome: TDSkButton
              Left = 0
              Top = 7
              Width = 120
              Height = 36
              ButtonText = 'Home'
              ButtonColor = xFF1976D2
              ButtonHover = xFF1565C0
              ButtonPressed = xFF1565C0
              ButtonDisabled = xFFE0E0E0
              ButtonChecked = xFF1565C0
              FontColor = claWhite
              FontHover = claWhite
              FontDisabled = xFF757575
              FontChecked = claWhite
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -19
              Font.Name = 'Microsoft YaHei UI'
              Font.Style = []
              ButtonStyle = bsRoundRect
              ButtonType = btNormal
              ButtonRound = 4.000000000000000000
              Checked = False
              ImageIndex = -1
              ImageAlign = iaLeft
              ImageMargin = 8
              BackgroundColor = claWhite
              BorderColor = claGray
              BorderWidth = 0.000000000000000000
            end
            object bgData: TDSkButton
              Left = 120
              Top = 7
              Width = 120
              Height = 36
              ButtonText = 'Data'
              ButtonColor = xFF1976D2
              ButtonHover = xFF1565C0
              ButtonPressed = xFF1565C0
              ButtonDisabled = xFFE0E0E0
              ButtonChecked = xFF1565C0
              FontColor = claWhite
              FontHover = claWhite
              FontDisabled = xFF757575
              FontChecked = claWhite
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -19
              Font.Name = 'Microsoft YaHei UI'
              Font.Style = []
              ButtonStyle = bsRoundRect
              ButtonType = btNormal
              ButtonRound = 4.000000000000000000
              Checked = False
              ImageIndex = -1
              ImageAlign = iaLeft
              ImageMargin = 8
              BackgroundColor = claWhite
              BorderColor = claGray
              BorderWidth = 0.000000000000000000
            end
            object bgSettings: TDSkButton
              Left = 240
              Top = 7
              Width = 120
              Height = 36
              ButtonText = 'Settings'
              ButtonColor = xFF1976D2
              ButtonHover = xFF1565C0
              ButtonPressed = xFF1565C0
              ButtonDisabled = xFFE0E0E0
              ButtonChecked = xFF1565C0
              FontColor = claWhite
              FontHover = claWhite
              FontDisabled = xFF757575
              FontChecked = claWhite
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -19
              Font.Name = 'Microsoft YaHei UI'
              Font.Style = []
              ButtonStyle = bsRoundRect
              ButtonType = btNormal
              ButtonRound = 4.000000000000000000
              Checked = False
              ImageIndex = -1
              ImageAlign = iaLeft
              ImageMargin = 8
              BackgroundColor = claWhite
              BorderColor = claGray
              BorderWidth = 0.000000000000000000
            end
          end
        end
      end
      object pnlRight: TDSkPanel
        Left = 644
        Top = 12
        Width = 420
        Height = 594
        Caption = ''
        CaptionPosition = cpTopLeft
        CaptionFont.Charset = DEFAULT_CHARSET
        CaptionFont.Color = clWindowText
        CaptionFont.Height = -12
        CaptionFont.Name = 'Microsoft YaHei'
        CaptionFont.Style = []
        CaptionMargin = 8.000000000000000000
        ChildPadding = 8.000000000000000000
        BackgroundHover = claWhitesmoke
        PanelStyle = psOutlined
        CornerRadius = 8.000000000000000000
        BackgroundColor = claWhite
        BorderColor = xFFE0E0E0
        BorderWidth = 1.000000000000000000
        object pnlStyleControl: TDSkPanel
          Left = 8
          Top = 8
          Width = 404
          Height = 90
          Caption = ''
          CaptionPosition = cpTopLeft
          CaptionFont.Charset = DEFAULT_CHARSET
          CaptionFont.Color = clWindowText
          CaptionFont.Height = -12
          CaptionFont.Name = 'Microsoft YaHei'
          CaptionFont.Style = []
          CaptionMargin = 4.000000000000000000
          ChildPadding = 4.000000000000000000
          BackgroundHover = claWhitesmoke
          PanelStyle = psOutlined
          CornerRadius = 6.000000000000000000
          BackgroundColor = claWhite
          BorderColor = xFFE0E0E0
          BorderWidth = 1.000000000000000000
          object rgStyle: TDSkRadioGroup
            Left = 6
            Top = 20
            Width = 392
            Height = 65
            Orientation = rgoHorizontal
            Items.Strings = (
              'Contained'
              'Outlined'
              'Text')
            Caption = 'Button Style'
            CaptionFont.Charset = DEFAULT_CHARSET
            CaptionFont.Color = -9079435
            CaptionFont.Height = -11
            CaptionFont.Name = 'Microsoft YaHei'
            CaptionFont.Style = [fsBold]
            CaptionMargin = 4.000000000000000000
            RadioSize = 16.000000000000000000
            ItemFont.Charset = DEFAULT_CHARSET
            ItemFont.Color = clWindowText
            ItemFont.Height = -12
            ItemFont.Name = 'Microsoft YaHei'
            ItemFont.Style = []
            OnItemClick = rgStyleItemClick
            BackgroundColor = claNull
            BorderColor = claGray
            BorderWidth = 0.000000000000000000
          end
        end
        object pnlStateControl: TDSkPanel
          Left = 8
          Top = 105
          Width = 404
          Height = 120
          Caption = ''
          CaptionPosition = cpTopLeft
          CaptionFont.Charset = DEFAULT_CHARSET
          CaptionFont.Color = clWindowText
          CaptionFont.Height = -12
          CaptionFont.Name = 'Microsoft YaHei'
          CaptionFont.Style = []
          CaptionMargin = 4.000000000000000000
          ChildPadding = 4.000000000000000000
          BackgroundHover = claWhitesmoke
          PanelStyle = psOutlined
          CornerRadius = 6.000000000000000000
          BackgroundColor = claWhite
          BorderColor = xFFE0E0E0
          BorderWidth = 1.000000000000000000
          object cbEnabled: TDSkCheckbox
            Left = 12
            Top = 24
            Width = 380
            Height = 24
            OnCheckChanged = cbEnabledCheckChanged
            Checked = True
            Caption = 'Enable Components'
            CheckboxSize = 16.000000000000000000
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Microsoft YaHei UI'
            Font.Style = []
          end
          object cbVisible: TDSkCheckbox
            Left = 12
            Top = 52
            Width = 380
            Height = 24
            OnCheckChanged = cbVisibleCheckChanged
            Checked = True
            Caption = 'Show Components'
            CheckboxSize = 16.000000000000000000
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Microsoft YaHei UI'
            Font.Style = []
          end
          object cbAnimated: TDSkCheckbox
            Left = 12
            Top = 80
            Width = 380
            Height = 24
            OnCheckChanged = cbAnimatedCheckChanged
            Checked = True
            Caption = 'Enable Animations'
            CheckboxSize = 16.000000000000000000
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Microsoft YaHei UI'
            Font.Style = []
          end
        end
        object btnReset: TDSkButton
          Left = 16
          Top = 540
          Width = 137
          Height = 32
          OnClick = btnResetClick
          ButtonText = 'Reset All'
          ButtonColor = xFF9C27B0
          ButtonHover = xFFBA68C8
          ButtonPressed = xFF7B1FA2
          ButtonDisabled = xFFBDBDBD
          ButtonChecked = xFF1565C0
          FontColor = claWhite
          FontHover = claWhite
          FontDisabled = xFF757575
          FontChecked = claWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -19
          Font.Name = 'Microsoft YaHei UI'
          Font.Style = []
          ButtonStyle = bsRoundRect
          ButtonType = btNormal
          ButtonRound = 10.000000000000000000
          Checked = False
          ImageIndex = -1
          ImageAlign = iaLeft
          ImageMargin = 8
          HoverEffect = heRipple
          MUIColorScheme = muiSecondary
          MUIStyle = muiContained
          BackgroundColor = claWhite
          BorderColor = xFF9C27B0
          BorderWidth = 0.000000000000000000
        end
      end
    end
  end
end
